version: '3.8'

services:
  postgres:
    build:
      context: ./postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example_db
    ports:
      - "0.0.0.0:5432:5432"  # ← слушает все интерфейсы (не только localhost)
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: >
      postgres -c shared_preload_libraries=pg_cron
               -c cron.database_name=example_db

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_db
    restart: always
    ports:
      - "0.0.0.0:8123:8123"  # HTTP-интерфейс (для клиентов типа DBeaver)
      - "0.0.0.0:9000:9000"  # Native-протокол (для clickhouse-client)
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      CLICKHOUSE_USER: user
      CLICKHOUSE_PASSWORD: strongpassword
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  mongo:
    image: mongo:6
    container_name: mongo_db
    restart: always
    ports:
      - "0.0.0.0:27017:27017"  # MongoDB слушает все интерфейсы
    volumes:
      - mongodb_data:/data/db

volumes:
  pgdata:
  clickhouse_data:
  mongodb_data: